# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8fa02e2929fa071157179b7154f1d81cea47eb5ebaf02bec52f5355edb242372558521dd1c80bb8ca2edb5a91f9a4090d736d6ad7b6286ab5e02ee5206c836b0

test:
  secret_key_base: 297ab4e9b0e8ca35ae64c93781847d980db926e6f5950d09f0b7e02b5fb62a84b43d66b456c30c4e35ab92fec14579baea43127522c74a7a83c01cf46a796a4f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
